wallpaper {
    monitor = eDP-1
    path = /home/travis/Pictures/Wallpapers/everforest/nature/fog_forest_1.png
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/travis/Pictures/Wallpapers/everforest/nature/fog_forest_1.png
}
splash = false
